Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile("C:/Users/Admin/.gemini/antigravity/brain/027bcca0-fc14-4b9f-a4c7-3e0deb776af5/.user_uploaded/media_1790070700400.png")
$size = [math]::Min($img.Width, $img.Height)
$x = [math]::Floor(($img.Width - $size) / 2)
$y = [math]::Floor(($img.Height - $size) / 2)
$rect = New-Object System.Drawing.Rectangle($x, $y, $size, $size)
$bmp = New-Object System.Drawing.Bitmap($size, $size)
$graphics = [System.Drawing.Graphics]::FromImage($bmp)
$graphics.DrawImage($img, (New-Object System.Drawing.Rectangle(0, 0, $size, $size)), $rect, [System.Drawing.GraphicsUnit]::Pixel)
$graphics.Dispose()
$img.Dispose()
$bmp.Save("d:\relationtree\src\app\icon.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Save("d:\relationtree\src\app\apple-icon.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
